# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mongmori' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mongmori

  pod 'NMapsMap'
  pod 'lottie-ios'
  pod 'Alamofire'
end
